"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math


def triangle(total, index, end):
    index = index + 1
    if index <= end:
        return triangle(total + index, index, end)
    else:
        return total, index - 1


def triangle_optima(n):
    if bool(n % 2 != 0):
        # x = 8 * 3 + 4
        return (n + 1) * (n / 2) + (n + 1) / 2
    else:
        return(n + 1) * (n / 2)


def find_divisors(num):
    divisors = set([num])

    for index in range(1, num):
        if num % index == 0:
            divisors.add(index)

    divisors = list(set(divisors))
    divisors.sort()
    return divisors


def divisors(num):
    divisors = set([1, num])
    ceiling = int(math.sqrt(num)) + 1
    for index in range(1, ceiling):
        if num % index == 0:
            divisors.add(index)
            divisors.add(num / index)
    return divisors


def triangle_num_with_min_divisors(triangle_index, current_divisors, min_divisors):
    while current_divisors <= min_divisors:
        triangle_index = triangle_index + 1
        triangle_number = triangle_optima(triangle_index)
        current_divisors = len(divisors(triangle_number))
        print(triangle_index, triangle_number, current_divisors)
    return triangle_number


"""
x, index = triangle(0, 0, 1900)
print(x, index)

divs = find_divisors(x)
print(divs)
print(len(divs))
"""
# x = triangle_optima(1000)

num = triangle_num_with_min_divisors(0, 0, 500)
print(num)

"""
x = divisors(100000)
print(x)
"""
